---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install docker==4.2.0
  - pip install molecule==2.22 # Molecule Installs Ansible
  - pip install ansible-lint==3.4.23
script:
  - ansible --version
  - molecule --version
  - docker -v
  - molecule $DEBUG test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
