---

- name: Install Gauntlt
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    #Gauntlt needs ruby installed
    ruby_version: 'ruby-2.3.1'
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_user: 'root'
    rvm1_install_path: '/usr/local/rvm'

  roles:
    - role: rvm.ruby
    - role: ansible-role-gauntlt
